### ISSUE TITLE
Stores/etc. to be created

### ISSUE THREAD

**Issue by arobillard** [arobillard/georgian-politics#7]
- [ ] Theatre(s)
- [ ] Apothecary/component store (scholar's row)
- [ ] Book store (sr)
- [ ] Paper store (sr)
- [ ] Bath house (city's crest)
```
  - title: 
    city-ref: 0
    district-ref:
    type-ref:
    owner:
    content: >-
```
